name: Build modules

on:
  push:
    paths:
      - '**/*.c'
      - '**/*.cpp'
      - '**/*.h'
      - '**/*.yml'
      - '**/Makefile'
      - '**/.sh'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Checkout SDK
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.my_token }}
        repository: GoldHEN/GoldHEN_Plugins_SDK
        path: SDK

    - name: Download OpenOrbis Toolchain
      run: |
        curl -fLOs https://github.com/illusion0001/OpenOrbis-PS4-Toolchain/releases/download/0.0.1.416/toolchain.tar.gz
        sudo apt install llvm lld
        tar xf toolchain.tar.gz
        echo "OO_PS4_TOOLCHAIN=$GITHUB_WORKSPACE/OpenOrbis/PS4Toolchain" >> $GITHUB_ENV
        ver="1.$(git rev-list HEAD --count)"
        echo "commit_ver=$ver" >> $GITHUB_ENV

    - name: Build SDK Lib
      working-directory: SDK
      run: |
        clang -v
        make
        echo "GOLDHEN_SDK=$GITHUB_WORKSPACE/SDK" >> $GITHUB_ENV

    - name: Build
      run: bash build.sh

    - name: Build
      run: bash build.sh 1

    - name: Push module artifact (release)
      uses: actions/upload-artifact@v3
      with:
        name: goldplugins_${{ env.commit_ver }}_prx_final
        path: bin/plugins/prx_final/*
        if-no-files-found: error
        retention-days: 7

    - name: Push module artifact (release original modules)
      uses: actions/upload-artifact@v3
      with:
        name: goldplugins_${{ env.commit_ver }}_elf_final
        path: bin/plugins/elf_final/*
        if-no-files-found: error
        retention-days: 7

    - name: Push module artifact (debug)
      uses: actions/upload-artifact@v3
      with:
        name: goldplugins_${{ env.commit_ver }}_prx_debug
        path: bin/plugins/prx_debug/*
        if-no-files-found: error
        retention-days: 7

    - name: Push module artifact (debug original modules)
      uses: actions/upload-artifact@v3
      with:
        name: goldplugins_${{ env.commit_ver }}_elf_debug
        path: bin/plugins/elf_debug/*
        if-no-files-found: error
        retention-days: 7
